project:
  type: website

website:
  title: "Job Market Analysis Group 3"
  navbar:
    left:
      - href: Introduction.qmd
        text: Introduction
      - href: Market_Trend.qmd
        text: Market Trends
      - href: Skill_Analysis.qmd
        text: Skill Analysis
      - href: Career_Strategy.qmd
        text: Career Strategy
      - href: Summary.qmd
        text: Summary
format:
  html:
    theme:
      - lumen
    css: styles.css
    toc: true
    number-sections: true



