project:
  type: website

website:
  title: "Job Market Analysis Group 3"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: data_analysis.ipynb
        text: Market Trends
      - href: Key_findings.qmd
        text: Skill Analysis
      - href: Career_Strategy.qmd
        text: Career Strategy
format:
  html:
    theme:
      - lumen
    css: styles.css
    toc: true
    number-sections: true



