project:
  type: website

website:
  title: "Job Market Analysis Group 3"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data_analysis.ipynb
        text: Data Analysis
format:
  html:
    theme:
      - lumen
    css: styles.css
    toc: true
    number-sections: true



