project:
  type: website

website:
  title: "Job Market Analysis Group 3"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: data_analysis.ipynb
        text: Data Analysis
      - href: Key_findings.qmd
        text: Key Findings
      - href: Summary.qmd
        text: Summary
format:
  html:
    theme:
      - lumen
    css: styles.css
    toc: true
    number-sections: true



