---
title: "Key Findings"
---

# PLOT 1 Geographic distribution of salary and job demand  state_map


# PLOT 2 Select (LOT_NAME_SPECIFIC) Mean Salary & Job Demand

This chart shows the number of job openings and average salaries for different professional positions. The dual-axis coordinates allow us to observe the relationship between supply, demand and strategic career path.

Data Analyst has the most job openings, indicating the strongest market demand, but the average salary is relatively medium, which is a position with a low entry threshold.

Enterprise Architect and Oracle Consultant/Analyst have few job openings, but the average salary is the highest, reflecting the skills are highly specialized and scarce.
   
Healthcare Analyst and Marketing Analyst have low salaries and fewer job openings, the positions with relatively limited demand and value.
   
General ERP Analyst/Consultant combines higher salaries with medium job openings, making it a career choice that balances compensation and opportunities.


# PLOT 3 Skill_radar_chart


# PLOT 4 Kmeans clustering for NAICS2_NAME skills (for Analyst position)

This figure reveals how different skill groups correspond to analyst positions. This insight helps align training, hiring, and upskilling strategies with industry-specific needs. 

Cluter 0 - Management, Data, Business, Analytics
Positions in this group tend to emphasize management and business logic skills. Positions may focus on data-driven decision making, project coordination, and report analysis. People with logical thinking and business sensitivity have a competitive advantage in this group.

Cluster 1 — Administrative and Office Support Skills (Microsoft, Data, Management, Excel, PowerPoint)
This group clearly prefers office practical skills and tool operation capabilities. This type of position has lower technical requirements and places more emphasis on detail processing and internal communication skills.

Cluster 2 — Hybrid Skill Group (Data, Management, Language, Programming, Business)
This is a group with obvious cross-skills, integrating data analysis, management, language communication and basic programming skills. Language skills and diverse backgrounds are particularly important in this group, suitable for people with communication skills + elementary programming + business perception.

Cluster 3 — Technology-oriented group (Programming, Data, SQL, Python)
This group is obviously highly technical, covering core skills (such as Programming, Python, and SQL.) These positions usually require strong programming and logic skills and suitable for computer, statistics, engineering backgrounds or those who have completed technical transformation training.


# PLOT 5 Random Forest 