<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Conclusion – Job Market Analysis Group 3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-58669c723890bbf731c346d0ef1150dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Job Market Analysis Group 3</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./Introduction.html"> 
<span class="menu-text">Introduction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Market_Trend.html"> 
<span class="menu-text">Market Trends</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Skill_Analysis.html"> 
<span class="menu-text">Skill Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Career_Strategy.html"> 
<span class="menu-text">Career Strategy</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Summary.html"> 
<span class="menu-text">Summary</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#current-trends-driving-the-importance-of-ai-and-data-skills" id="toc-current-trends-driving-the-importance-of-ai-and-data-skills" class="nav-link" data-scroll-target="#current-trends-driving-the-importance-of-ai-and-data-skills"><span class="header-section-number">1.1</span> Current Trends Driving the Importance of AI and Data Skills</a></li>
  <li><a href="#expected-findings-and-analytical-focus" id="toc-expected-findings-and-analytical-focus" class="nav-link" data-scroll-target="#expected-findings-and-analytical-focus"><span class="header-section-number">1.2</span> Expected Findings and Analytical Focus</a></li>
  </ul></li>
  <li><a href="#literature" id="toc-literature" class="nav-link" data-scroll-target="#literature"><span class="header-section-number">2</span> Literature</a></li>
  <li><a href="#geographic-distribution-of-salary-and-job-demand-state_map" id="toc-geographic-distribution-of-salary-and-job-demand-state_map" class="nav-link" data-scroll-target="#geographic-distribution-of-salary-and-job-demand-state_map"><span class="header-section-number">3</span> Geographic distribution of salary and job demand state_map</a></li>
  <li><a href="#select-lot_name_specific-mean-salary-job-demand" id="toc-select-lot_name_specific-mean-salary-job-demand" class="nav-link" data-scroll-target="#select-lot_name_specific-mean-salary-job-demand"><span class="header-section-number">4</span> Select (LOT_NAME_SPECIFIC) Mean Salary &amp; Job Demand</a></li>
  <li><a href="#skills-radar-chart" id="toc-skills-radar-chart" class="nav-link" data-scroll-target="#skills-radar-chart"><span class="header-section-number">5</span> Skills radar chart</a></li>
  <li><a href="#skill-evaluation" id="toc-skill-evaluation" class="nav-link" data-scroll-target="#skill-evaluation"><span class="header-section-number">6</span> Skill Evaluation</a>
  <ul class="collapse">
  <li><a href="#marcos-skills-evaluation" id="toc-marcos-skills-evaluation" class="nav-link" data-scroll-target="#marcos-skills-evaluation"><span class="header-section-number">6.1</span> Marco’s Skills Evaluation</a>
  <ul class="collapse">
  <li><a href="#millies-skills-evaluation" id="toc-millies-skills-evaluation" class="nav-link" data-scroll-target="#millies-skills-evaluation"><span class="header-section-number">6.1.1</span> Millie’s Skills Evaluation</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#kmeans-clustering-for-naics2_name-skills-for-analyst-position" id="toc-kmeans-clustering-for-naics2_name-skills-for-analyst-position" class="nav-link" data-scroll-target="#kmeans-clustering-for-naics2_name-skills-for-analyst-position"><span class="header-section-number">7</span> Kmeans clustering for NAICS2_NAME skills (for Analyst position)</a></li>
  <li><a href="#random-forest" id="toc-random-forest" class="nav-link" data-scroll-target="#random-forest"><span class="header-section-number">8</span> Random Forest</a>
  <ul class="collapse">
  <li><a href="#model-design-process" id="toc-model-design-process" class="nav-link" data-scroll-target="#model-design-process"><span class="header-section-number">8.1</span> Model Design Process</a></li>
  <li><a href="#performance-and-assessment" id="toc-performance-and-assessment" class="nav-link" data-scroll-target="#performance-and-assessment"><span class="header-section-number">8.2</span> Performance and Assessment</a></li>
  <li><a href="#strategic-use-of-the-random-forest-model" id="toc-strategic-use-of-the-random-forest-model" class="nav-link" data-scroll-target="#strategic-use-of-the-random-forest-model"><span class="header-section-number">8.3</span> Strategic Use of the Random Forest Model</a></li>
  <li><a href="#educational-development" id="toc-educational-development" class="nav-link" data-scroll-target="#educational-development"><span class="header-section-number">14.1</span> Educational Development</a></li>
  <li><a href="#project-based-application" id="toc-project-based-application" class="nav-link" data-scroll-target="#project-based-application"><span class="header-section-number">14.2</span> Project-Based Application</a></li>
  <li><a href="#skills-to-improve" id="toc-skills-to-improve" class="nav-link" data-scroll-target="#skills-to-improve"><span class="header-section-number">14.3</span> Skills to Improve</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-notebooks"><h2>Notebooks</h2><ul><li><a href="data_analysis-preview.html"><i class="bi bi-journal-code"></i>PLOT 2  Select (LOT_NAME_SPECIFIC) Mean Salary &amp; Job Demand</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Conclusion</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">today</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>The significance of this topic stems from the accelerating evolution of data science, business analytics, and machine learning in today’s digital economy. According to According to <span class="citation" data-cites="pwc2024barometer">PwC (<a href="#ref-pwc2024barometer" role="doc-biblioref">(2024)</a>)</span>, AI-related job skills are evolving 66% faster than those in non-AI sectors, signaling a profound transformation in the job market. , AI-related job skills are evolving 66% faster than those in non-AI sectors, signaling a profound transformation in the job market. As organizations generate unprecedented volumes of data, the ability to interpret, manage, and extract actionable insights from this data has become an indispensable capability. AI technologies are no longer confined to research labs—they are now deeply embedded in daily business operations, creating new opportunities across a wide range of industries. In this context, understanding the emerging skills and trends is not only essential for current job readiness but also for influencing the future of work and business innovation.</p>
<section id="current-trends-driving-the-importance-of-ai-and-data-skills" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="current-trends-driving-the-importance-of-ai-and-data-skills"><span class="header-section-number">1.1</span> Current Trends Driving the Importance of AI and Data Skills</h2>
<p>In 2024, the integration of artificial intelligence and machine learning into core business strategies has intensified the demand for professionals proficient in developing, deploying, and optimizing AI systems. Key competencies now include mastery of machine learning algorithms, data engineering, and the implementation of scalable AI models. For instance, companies like Meta are increasingly investing in professionals who can support large-scale AI initiatives through advanced model development and data pipeline automation <span class="citation" data-cites="time2024meta">(<a href="#ref-time2024meta" role="doc-biblioref">Allyn (2024)</a>)</span>. Moreover, as automation becomes more pervasive, skills in predictive analytics, process automation, and data-informed decision-making are becoming crucial across sectors. The convergence of big data technologies, AI solutions, and industry-specific expertise marks a pivotal shift in workforce requirements, with these capabilities emerging as critical assets in a rapidly transforming job market.</p>
</section>
<section id="expected-findings-and-analytical-focus" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="expected-findings-and-analytical-focus"><span class="header-section-number">1.2</span> Expected Findings and Analytical Focus</h2>
<p>Through our analysis, we aim to identify the essential technical and strategic skills shaping the future of data science, business analytics, and machine learning. We anticipate a pronounced focus on machine learning expertise, particularly regarding algorithm design and model deployment. As the demand for data-literate professionals continues to surge, familiarity with big data ecosystems and decision-support platforms will be increasingly vital. Furthermore, we expect industry verticals such as retail, finance, and healthcare to demonstrate a growing reliance on domain-specific analytics to enhance operational efficiency and guide strategic planning. These findings will provide valuable insights into the evolving skill sets necessary for success in a data-driven, AI-augmented business environment.</p>
</section>
</section>
<section id="literature" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Literature</h1>
<p>With the objective of gaining better understanding of current trends within the AI and data science job market, a short literature review was performed. Three key studies have been selected to illustrate the current landscape and future directions of job skills in this domain.</p>
<p>In the first study, a large-scale analysis of U.S. job postings was done to examine the impact generative AI adoption has on skill requirements. Findings indicate that roles incorporating generative AI <strong>demand 36.7% higher levels of cognitive skills, including critical thinking and complex problem-solving</strong>, as well as a 5.2% increase in social skills such as collaboration and communication. This evidence suggests a paradigm shift in hiring practices, wherein employers prioritize candidates who combine technical proficiency with advanced interpersonal and analytical capabilities <span class="citation" data-cites="gulati2025generative">Gulati, Venkataraman, and Raj (<a href="#ref-gulati2025generative" role="doc-biblioref">(2025)</a>)</span>.</p>
<p>The second study we found highlights the growing importance of machine learning and Python programming in data science job postings. The analysis reveals that <strong>69% of job advertisements explicitly require machine learning competencies</strong>, while <strong>78% mention Python</strong>. This trend underscores the transition of AI and ML literacy from specialized expertise to essential qualifications for data-centric roles, reflecting the centrality of these technologies in organizational strategy and operations <span class="citation" data-cites="cobloom2025datascience">Cobloom (<a href="#ref-cobloom2025datascience" role="doc-biblioref">(2025)</a>)</span>.</p>
<p>Finally, the third study analyzed differences in wage associated with educational attainment and practical skill acquisition in AI-related employment. Their study reveals that <strong>demonstrated competencies, such as certifications and project-based experience, confer a 23% wage premium, compared to a 15% premium for formal degrees alone</strong>. This differential underscores the increasing importance of skills-based credentials as more reliable indicators of job readiness and value creation in AI-driven labor markets <span class="citation" data-cites="bone2023skills">Bone, Conroy, and Tan (<a href="#ref-bone2023skills" role="doc-biblioref">(2023)</a>)</span>.</p>
<p>To conclude the review, these studies collectively highlight distinct aspects of market hiring behavior, revealing a shift towards skills-based hiring, the importance of knowing machine learning and Python programming, and the increasing value placed on cognitive skills. From the findings we can start to change the way we think about job searching and adjust our strategies to align with the evolving demands of the job market.</p>
</section>
<section id="geographic-distribution-of-salary-and-job-demand-state_map" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Geographic distribution of salary and job demand state_map</h1>
<iframe width="780" height="600" src="./output/figures/state_map.html" title="Geographic distribution of salary and job demand"></iframe>
<p>In order to generate valuable and actionable insights there need to be a general understanding of the job market. The following chart shows the geographic distribution of salary and job demand across the United States. The salary plot reveals that the Northeastern region holds the cluster of states with the highest average salaries with Connecticut, Vermont, and New Jersey being the top three. The job demand plot shows great disparity in job openings across the country with Texas and California being the top job generators. It is important to note that the graphs dont answer many questions about the job market, but instead provide a starting point for deeper analysis. Here we can begin exploring the data with specific goals in mind, actionability for career strategy design.</p>
</section>
<section id="select-lot_name_specific-mean-salary-job-demand" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Select (LOT_NAME_SPECIFIC) Mean Salary &amp; Job Demand</h1>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/Select_Mean Salary&amp;Job Demand.png" class="img-fluid figure-img"></p>
<figcaption>Select (LOT_NAME_SPECIFIC) Mean Salary &amp; Job Demand</figcaption>
</figure>
</div>
<p>This chart shows the number of job openings and average salaries for different professional positions. The dual-axis coordinates allow us to observe the relationship between supply, demand and strategic career path.</p>
<p>Among various analyst roles, Data Analyst positions show <strong>the highest number of job openings, reflecting strong market demand and suggesting a relatively low barrier to entry</strong>. In contrast, Enterprise Architects and Oracle Consultants/Analysts command <strong>the highest average salaries despite limited openings, indicating that these roles require highly specialized and scarce skill sets</strong>. Healthcare Analysts and Marketing Analysts are associated with <strong>both lower salaries and fewer opportunities, suggesting more limited market demand.</strong> Meanwhile, General ERP Analysts/Consultants strike a balance—offering relatively high salaries along with a moderate number of job openings—making them attractive for professionals seeking both compensation and career opportunity.</p>
</section>
<section id="skills-radar-chart" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Skills radar chart</h1>
<iframe width="780" height="600" src="./output/figures/skill_radar_chart.html" title="Skill_radar_chart"></iframe>
</section>
<section id="skill-evaluation" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Skill Evaluation</h1>
<section id="marcos-skills-evaluation" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="marcos-skills-evaluation"><span class="header-section-number">6.1</span> Marco’s Skills Evaluation</h2>
<p>This radar chart illustrates Marco’s self-assessed proficiency across a broad range of analyst-related skills. Overall, he demonstrates strong capabilities in <strong>communication, problem solving, detail orientation, leadership, and research, each rated at level 4</strong>, highlighting excellent readiness for collaborative work, analytical thinking, and stakeholder engagement.</p>
<p>Marco shows moderate competence in management, Microsoft Excel, data visualization, and presentations, with scores around level 3, indicating a solid foundation in core business skills and common data workflows.</p>
<p>On the technical side, his proficiency in <strong>Python, SQL, Tableau, Power BI, statistics, and data management mostly falls between levels 2 and 3</strong>, suggesting basic familiarity with these critical tools. Developing deeper technical expertise through targeted training, certifications, or applied project work would help strengthen his profile for data-intensive roles.</p>
<p>In summary, Marco combines strong soft skills, high logical thinking, and business-focused capabilities. If technical skills were further developed, he would be especially well suited for roles that emphasize stakeholder engagement, problem solving, and translating data insights into strategic recommendations.</p>
<section id="millies-skills-evaluation" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="millies-skills-evaluation"><span class="header-section-number">6.1.1</span> Millie’s Skills Evaluation</h3>
<p>This radar chart illustrates Millie’s self-assessed proficiency across a range of analyst-related skills. Overall, she demonstrates strong capabilities in <strong>communication, management, and Microsoft Excel, each rated at 4</strong>, indicating solid workplace readiness and strong collaboration skills.</p>
<p>Millie also shows competence in areas like data management, data visualization, problem solving, and leadership, with scores generally around 3, suggesting she has a solid foundation in analytical thinking and business-related soft skills.</p>
<p>On the technical side, her proficiency in tools such as <strong>SQL, Python, Tableau, Power BI, and statistics ranges between 2 and 3</strong>, reflecting basic familiarity with room for growth. These skills can be strengthened through hands-on project work or further technical training.</p>
<p>In summary, Millie is a promising early-career analyst with strong soft skills and business tool proficiency, and she is actively developing her technical analytics skillset. She would thrive in roles that bridge communication and data, with clear potential to grow into a well-rounded data analyst.</p>
<section id="summary" class="level4" data-number="6.1.1.1">
<h4 data-number="6.1.1.1" class="anchored" data-anchor-id="summary"><span class="header-section-number">6.1.1.1</span> Summary</h4>
<p>Based on the skill assessment results, Marco and Millie are able to clearly identify their strengths and areas for improvement. This evaluation provides a valuable foundation for them to take targeted actions—whether by enhancing technical skills through training or leveraging existing strengths in communication and management to further optimize their capabilities and better align with their career goals.</p>
</section>
</section>
</section>
</section>
<section id="kmeans-clustering-for-naics2_name-skills-for-analyst-position" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Kmeans clustering for NAICS2_NAME skills (for Analyst position)</h1>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/Find_best_K.png" class="img-fluid figure-img"></p>
<figcaption>Select Two Way Find Best K</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/Kmeans_clustering_for_skills.png" class="img-fluid figure-img"></p>
<figcaption>Select (LOT_NAME_SPECIFIC) Mean Salary &amp; Job Demand</figcaption>
</figure>
</div>
<p>This figure reveals how different skill groups correspond to analyst positions. This insight helps align training, hiring, and upskilling strategies with industry-specific needs.</p>
<p>Cluter 0 - Management, Data, Business, Analytics Positions in this group tend to <strong>emphasize management and business logic skills</strong>. Positions may focus on data-driven decision making, project coordination, and report analysis. People with <strong>logical thinking and business sensitivity</strong> have a competitive advantage in this group.</p>
<p>Cluster 1 — Administrative and Office Support Skills (Microsoft, Data, Management, Excel, PowerPoint) This group clearly prefers office <strong>practical skills and tool operation capabilities</strong>. This type of position has lower technical requirements and places more <strong>emphasis on detail processing and internal communication skills</strong>.</p>
<p>Cluster 2 — Hybrid Skill Group (Data, Management, Language, Programming, Business) This is a group with <strong>obvious cross-skills, integrating data analysis, management, language communication and basic programming skills</strong>. Language skills and diverse backgrounds are particularly important in this group, suitable for people with communication skills + elementary programming + business perception.</p>
<p>Cluster 3 — Technology-oriented group This group is obviously <strong>highly technical, covering core skills (such as Programming, Python, and SQL.)</strong> These positions usually require strong programming and logic skills and suitable for computer, statistics, engineering backgrounds or those who have completed technical transformation training.</p>
</section>
<section id="random-forest" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Random Forest</h1>
<section id="model-design-process" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="model-design-process"><span class="header-section-number">8.1</span> Model Design Process</h2>
<p>Below is an illustration of how the Random Forest model was designed in order to predict the salary of an analyst position based on a list of skills.</p>
<p><img src="output/figures/RF_slide.png" class="img-fluid"></p>
</section>
<section id="performance-and-assessment" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="performance-and-assessment"><span class="header-section-number">8.2</span> Performance and Assessment</h2>
<p>After developing the model we assessed its performance using the following metrics:</p>
<pre><code>    RMSE: $24,094.44
    Interpretation: Predicted salaries deviate from actual salaries by approximately $24,094. Lower RMSE indicates better accuracy.

    R²: 0.635
    Interpretation: The model explains 63.5% of the variation in salaries based on the input features. Higher R² reflects stronger predictive power.

    Predicted Salary: $91,979.83
    Skills used: ["communication", "time_management", "team_leadership", "problem_solving", "critical_thinking","detail_oriented", "innovation", "data_analysis", "statistical_modeling", "dashboard", "power_bi", "etl",
    "python_", "sql_", "microsoft_excel"]</code></pre>
</section>
<section id="strategic-use-of-the-random-forest-model" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="strategic-use-of-the-random-forest-model"><span class="header-section-number">8.3</span> Strategic Use of the Random Forest Model</h2>
<p>The Random Forest regression model estimated an expected salary of $91,979.83 using a defined set of 15 skills transformed into binary vector inputs. The RMSE of approximately $24,094 indicates individual salaries may differ substantially due to unmeasured factors. However, the R² value of 0.635 demonstrates that the model is able to capture over 60% of the variation in salaries even with the limited focus on skills alone.</p>
<p>From the beginning, this model was designed to facilitate actionability in the short term. That is why other features such as education level and minimum years of experience were not considered, because they wouldn’t be something that could be easily changed. However, location data (state) was tested as this is a decision one could make when searching for jobs but ultimately excluded because it reduced model performance and added complexity without a proportional gain in precision. The emphasis on modifiable inputs—skills rather than static traits—enables actionable insights for users who want to understand how improving competencies can impact compensation over time. Additionally, selecting only the top 100 skills from the dataset enhances the model’s performance and the users’ benefit from it.</p>
<p>Overall, the model functions as a practical guidance tool, as envisioned, rather than a pinpoint prediction. It offers a way to inform career planning, prioritize skill development, and benchmark earning potential, providing directional insights (a compass) rather than precise estimates (a coordinate).</p>
<div class="quarto-embed-nb-cell">
<div id="bed9e175" class="cell" data-execution_count="2">
<div class="cell-output cell-output-stdout">
<pre><code>---This is Diagnostic check, No need to print it in the final doc---
root
 |-- ID: string (nullable = true)
 |-- LAST_UPDATED_DATE: string (nullable = true)
 |-- LAST_UPDATED_TIMESTAMP: timestamp (nullable = true)
 |-- DUPLICATES: integer (nullable = true)
 |-- POSTED: string (nullable = true)
 |-- EXPIRED: string (nullable = true)
 |-- DURATION: integer (nullable = true)
 |-- SOURCE_TYPES: string (nullable = true)
 |-- SOURCES: string (nullable = true)
 |-- URL: string (nullable = true)
 |-- ACTIVE_URLS: string (nullable = true)
 |-- ACTIVE_SOURCES_INFO: string (nullable = true)
 |-- TITLE_RAW: string (nullable = true)
 |-- BODY: string (nullable = true)
 |-- MODELED_EXPIRED: string (nullable = true)
 |-- MODELED_DURATION: integer (nullable = true)
 |-- COMPANY: integer (nullable = true)
 |-- COMPANY_NAME: string (nullable = true)
 |-- COMPANY_RAW: string (nullable = true)
 |-- COMPANY_IS_STAFFING: boolean (nullable = true)
 |-- EDUCATION_LEVELS: string (nullable = true)
 |-- EDUCATION_LEVELS_NAME: string (nullable = true)
 |-- MIN_EDULEVELS: integer (nullable = true)
 |-- MIN_EDULEVELS_NAME: string (nullable = true)
 |-- MAX_EDULEVELS: integer (nullable = true)
 |-- MAX_EDULEVELS_NAME: string (nullable = true)
 |-- EMPLOYMENT_TYPE: integer (nullable = true)
 |-- EMPLOYMENT_TYPE_NAME: string (nullable = true)
 |-- MIN_YEARS_EXPERIENCE: integer (nullable = true)
 |-- MAX_YEARS_EXPERIENCE: integer (nullable = true)
 |-- IS_INTERNSHIP: boolean (nullable = true)
 |-- SALARY: integer (nullable = true)
 |-- REMOTE_TYPE: integer (nullable = true)
 |-- REMOTE_TYPE_NAME: string (nullable = true)
 |-- ORIGINAL_PAY_PERIOD: string (nullable = true)
 |-- SALARY_TO: integer (nullable = true)
 |-- SALARY_FROM: integer (nullable = true)
 |-- LOCATION: string (nullable = true)
 |-- CITY: string (nullable = true)
 |-- CITY_NAME: string (nullable = true)
 |-- COUNTY: integer (nullable = true)
 |-- COUNTY_NAME: string (nullable = true)
 |-- MSA: integer (nullable = true)
 |-- MSA_NAME: string (nullable = true)
 |-- STATE: integer (nullable = true)
 |-- STATE_NAME: string (nullable = true)
 |-- COUNTY_OUTGOING: integer (nullable = true)
 |-- COUNTY_NAME_OUTGOING: string (nullable = true)
 |-- COUNTY_INCOMING: integer (nullable = true)
 |-- COUNTY_NAME_INCOMING: string (nullable = true)
 |-- MSA_OUTGOING: integer (nullable = true)
 |-- MSA_NAME_OUTGOING: string (nullable = true)
 |-- MSA_INCOMING: integer (nullable = true)
 |-- MSA_NAME_INCOMING: string (nullable = true)
 |-- NAICS2: integer (nullable = true)
 |-- NAICS2_NAME: string (nullable = true)
 |-- NAICS3: integer (nullable = true)
 |-- NAICS3_NAME: string (nullable = true)
 |-- NAICS4: integer (nullable = true)
 |-- NAICS4_NAME: string (nullable = true)
 |-- NAICS5: integer (nullable = true)
 |-- NAICS5_NAME: string (nullable = true)
 |-- NAICS6: integer (nullable = true)
 |-- NAICS6_NAME: string (nullable = true)
 |-- TITLE: string (nullable = true)
 |-- TITLE_NAME: string (nullable = true)
 |-- TITLE_CLEAN: string (nullable = true)
 |-- SKILLS: string (nullable = true)
 |-- SKILLS_NAME: string (nullable = true)
 |-- SPECIALIZED_SKILLS: string (nullable = true)
 |-- SPECIALIZED_SKILLS_NAME: string (nullable = true)
 |-- CERTIFICATIONS: string (nullable = true)
 |-- CERTIFICATIONS_NAME: string (nullable = true)
 |-- COMMON_SKILLS: string (nullable = true)
 |-- COMMON_SKILLS_NAME: string (nullable = true)
 |-- SOFTWARE_SKILLS: string (nullable = true)
 |-- SOFTWARE_SKILLS_NAME: string (nullable = true)
 |-- ONET: string (nullable = true)
 |-- ONET_NAME: string (nullable = true)
 |-- ONET_2019: string (nullable = true)
 |-- ONET_2019_NAME: string (nullable = true)
 |-- CIP6: string (nullable = true)
 |-- CIP6_NAME: string (nullable = true)
 |-- CIP4: string (nullable = true)
 |-- CIP4_NAME: string (nullable = true)
 |-- CIP2: string (nullable = true)
 |-- CIP2_NAME: string (nullable = true)
 |-- SOC_2021_2: string (nullable = true)
 |-- SOC_2021_2_NAME: string (nullable = true)
 |-- SOC_2021_3: string (nullable = true)
 |-- SOC_2021_3_NAME: string (nullable = true)
 |-- SOC_2021_4: string (nullable = true)
 |-- SOC_2021_4_NAME: string (nullable = true)
 |-- SOC_2021_5: string (nullable = true)
 |-- SOC_2021_5_NAME: string (nullable = true)
 |-- LOT_CAREER_AREA: integer (nullable = true)
 |-- LOT_CAREER_AREA_NAME: string (nullable = true)
 |-- LOT_OCCUPATION: integer (nullable = true)
 |-- LOT_OCCUPATION_NAME: string (nullable = true)
 |-- LOT_SPECIALIZED_OCCUPATION: integer (nullable = true)
 |-- LOT_SPECIALIZED_OCCUPATION_NAME: string (nullable = true)
 |-- LOT_OCCUPATION_GROUP: integer (nullable = true)
 |-- LOT_OCCUPATION_GROUP_NAME: string (nullable = true)
 |-- LOT_V6_SPECIALIZED_OCCUPATION: integer (nullable = true)
 |-- LOT_V6_SPECIALIZED_OCCUPATION_NAME: string (nullable = true)
 |-- LOT_V6_OCCUPATION: integer (nullable = true)
 |-- LOT_V6_OCCUPATION_NAME: string (nullable = true)
 |-- LOT_V6_OCCUPATION_GROUP: integer (nullable = true)
 |-- LOT_V6_OCCUPATION_GROUP_NAME: string (nullable = true)
 |-- LOT_V6_CAREER_AREA: integer (nullable = true)
 |-- LOT_V6_CAREER_AREA_NAME: string (nullable = true)
 |-- SOC_2: string (nullable = true)
 |-- SOC_2_NAME: string (nullable = true)
 |-- SOC_3: string (nullable = true)
 |-- SOC_3_NAME: string (nullable = true)
 |-- SOC_4: string (nullable = true)
 |-- SOC_4_NAME: string (nullable = true)
 |-- SOC_5: string (nullable = true)
 |-- SOC_5_NAME: string (nullable = true)
 |-- LIGHTCAST_SECTORS: string (nullable = true)
 |-- LIGHTCAST_SECTORS_NAME: string (nullable = true)
 |-- NAICS_2022_2: integer (nullable = true)
 |-- NAICS_2022_2_NAME: string (nullable = true)
 |-- NAICS_2022_3: integer (nullable = true)
 |-- NAICS_2022_3_NAME: string (nullable = true)
 |-- NAICS_2022_4: integer (nullable = true)
 |-- NAICS_2022_4_NAME: string (nullable = true)
 |-- NAICS_2022_5: integer (nullable = true)
 |-- NAICS_2022_5_NAME: string (nullable = true)
 |-- NAICS_2022_6: integer (nullable = true)
 |-- NAICS_2022_6_NAME: string (nullable = true)
</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+--------------------+-----------------+----------------------+----------+--------+---------+--------+--------------------+--------------------+--------------------+-----------+-------------------+--------------------+--------------------+---------------+----------------+--------+--------------------+-----------+-------------------+----------------+---------------------+-------------+-------------------+-------------+------------------+---------------+--------------------+--------------------+--------------------+-------------+------+-----------+----------------+-------------------+---------+-----------+--------------------+--------------------+-------------+------+--------------+-----+--------------------+-----+----------+---------------+--------------------+---------------+--------------------+------------+--------------------+------------+--------------------+------+--------------------+------+--------------------+------+--------------------+------+--------------------+------+--------------------+------------------+-------------------+--------------------+--------------------+--------------------+--------------------+-----------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+----------+--------------------+----------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+----------+--------------------+----------+--------------------+----------+---------------+----------+---------------+---------------+--------------------+--------------+--------------------+--------------------------+-------------------------------+--------------------+-------------------------+-----------------------------+----------------------------------+-----------------+----------------------+-----------------------+----------------------------+------------------+-----------------------+-------+--------------------+-------+--------------------+-------+---------------+-------+---------------+-----------------+----------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+
|                  ID|LAST_UPDATED_DATE|LAST_UPDATED_TIMESTAMP|DUPLICATES|  POSTED|  EXPIRED|DURATION|        SOURCE_TYPES|             SOURCES|                 URL|ACTIVE_URLS|ACTIVE_SOURCES_INFO|           TITLE_RAW|                BODY|MODELED_EXPIRED|MODELED_DURATION| COMPANY|        COMPANY_NAME|COMPANY_RAW|COMPANY_IS_STAFFING|EDUCATION_LEVELS|EDUCATION_LEVELS_NAME|MIN_EDULEVELS| MIN_EDULEVELS_NAME|MAX_EDULEVELS|MAX_EDULEVELS_NAME|EMPLOYMENT_TYPE|EMPLOYMENT_TYPE_NAME|MIN_YEARS_EXPERIENCE|MAX_YEARS_EXPERIENCE|IS_INTERNSHIP|SALARY|REMOTE_TYPE|REMOTE_TYPE_NAME|ORIGINAL_PAY_PERIOD|SALARY_TO|SALARY_FROM|            LOCATION|                CITY|    CITY_NAME|COUNTY|   COUNTY_NAME|  MSA|            MSA_NAME|STATE|STATE_NAME|COUNTY_OUTGOING|COUNTY_NAME_OUTGOING|COUNTY_INCOMING|COUNTY_NAME_INCOMING|MSA_OUTGOING|   MSA_NAME_OUTGOING|MSA_INCOMING|   MSA_NAME_INCOMING|NAICS2|         NAICS2_NAME|NAICS3|         NAICS3_NAME|NAICS4|         NAICS4_NAME|NAICS5|         NAICS5_NAME|NAICS6|         NAICS6_NAME|             TITLE|         TITLE_NAME|         TITLE_CLEAN|              SKILLS|         SKILLS_NAME|  SPECIALIZED_SKILLS|SPECIALIZED_SKILLS_NAME|      CERTIFICATIONS| CERTIFICATIONS_NAME|       COMMON_SKILLS|  COMMON_SKILLS_NAME|     SOFTWARE_SKILLS|SOFTWARE_SKILLS_NAME|      ONET|           ONET_NAME| ONET_2019|      ONET_2019_NAME|                CIP6|           CIP6_NAME|                CIP4|           CIP4_NAME|                CIP2|           CIP2_NAME|SOC_2021_2|     SOC_2021_2_NAME|SOC_2021_3|     SOC_2021_3_NAME|SOC_2021_4|SOC_2021_4_NAME|SOC_2021_5|SOC_2021_5_NAME|LOT_CAREER_AREA|LOT_CAREER_AREA_NAME|LOT_OCCUPATION| LOT_OCCUPATION_NAME|LOT_SPECIALIZED_OCCUPATION|LOT_SPECIALIZED_OCCUPATION_NAME|LOT_OCCUPATION_GROUP|LOT_OCCUPATION_GROUP_NAME|LOT_V6_SPECIALIZED_OCCUPATION|LOT_V6_SPECIALIZED_OCCUPATION_NAME|LOT_V6_OCCUPATION|LOT_V6_OCCUPATION_NAME|LOT_V6_OCCUPATION_GROUP|LOT_V6_OCCUPATION_GROUP_NAME|LOT_V6_CAREER_AREA|LOT_V6_CAREER_AREA_NAME|  SOC_2|          SOC_2_NAME|  SOC_3|          SOC_3_NAME|  SOC_4|     SOC_4_NAME|  SOC_5|     SOC_5_NAME|LIGHTCAST_SECTORS|LIGHTCAST_SECTORS_NAME|NAICS_2022_2|   NAICS_2022_2_NAME|NAICS_2022_3|   NAICS_2022_3_NAME|NAICS_2022_4|   NAICS_2022_4_NAME|NAICS_2022_5|   NAICS_2022_5_NAME|NAICS_2022_6|   NAICS_2022_6_NAME|
+--------------------+-----------------+----------------------+----------+--------+---------+--------+--------------------+--------------------+--------------------+-----------+-------------------+--------------------+--------------------+---------------+----------------+--------+--------------------+-----------+-------------------+----------------+---------------------+-------------+-------------------+-------------+------------------+---------------+--------------------+--------------------+--------------------+-------------+------+-----------+----------------+-------------------+---------+-----------+--------------------+--------------------+-------------+------+--------------+-----+--------------------+-----+----------+---------------+--------------------+---------------+--------------------+------------+--------------------+------------+--------------------+------+--------------------+------+--------------------+------+--------------------+------+--------------------+------+--------------------+------------------+-------------------+--------------------+--------------------+--------------------+--------------------+-----------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+----------+--------------------+----------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+----------+--------------------+----------+--------------------+----------+---------------+----------+---------------+---------------+--------------------+--------------+--------------------+--------------------------+-------------------------------+--------------------+-------------------------+-----------------------------+----------------------------------+-----------------+----------------------+-----------------------+----------------------------+------------------+-----------------------+-------+--------------------+-------+--------------------+-------+---------------+-------+---------------+-----------------+----------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+
|1f57d95acf4dc67ed...|         9/6/2024|  2024-09-06 20:32:...|         0|6/2/2024| 6/8/2024|       6|   [\n  "Company"\n]|[\n  "brassring.c...|[\n  "https://sjo...|         []|               NULL|Enterprise Analys...|31-May-2024\n\nEn...|       6/8/2024|               6|  894731|          Murphy USA| Murphy USA|              false|       [\n  2\n]| [\n  "Bachelor's ...|            2|  Bachelor's degree|         NULL|              NULL|              1|Full-time (&gt; 32 h...|                   2|                   2|        false|  NULL|          0|          [None]|               NULL|     NULL|       NULL|{\n  "lat": 33.20...|RWwgRG9yYWRvLCBBUg==|El Dorado, AR|  5139|     Union, AR|20980|       El Dorado, AR|    5|  Arkansas|           5139|           Union, AR|           5139|           Union, AR|       20980|       El Dorado, AR|       20980|       El Dorado, AR|    44|        Retail Trade|   441|Motor Vehicle and...|  4413|Automotive Parts,...| 44133|Automotive Parts ...|441330|Automotive Parts ...|ET29C073C03D1F86B4|Enterprise Analysts|enterprise analys...|[\n  "KS126DB6T06...|[\n  "Merchandisi...|[\n  "KS126DB6T06...|   [\n  "Merchandisi...|                  []|                  []|[\n  "KS126706DPF...|[\n  "Mathematics...|[\n  "KS440W865GC...|[\n  "SQL (Progra...|15-2051.01|Business Intellig...|15-2051.01|Business Intellig...|[\n  "45.0601",\n...|[\n  "Economics, ...|[\n  "45.06",\n  ...|[\n  "Economics",...|[\n  "45",\n  "27...|[\n  "Social Scie...|   15-0000|Computer and Math...|   15-2000|Mathematical Scie...|   15-2050|Data Scientists|   15-2051|Data Scientists|             23|Information Techn...|        231010|Business Intellig...|                  23101011|           General ERP Analy...|                2310|     Business Intellig...|                     23101011|              General ERP Analy...|           231010|  Business Intellig...|                   2310|        Business Intellig...|                23|   Information Techn...|15-0000|Computer and Math...|15-2000|Mathematical Scie...|15-2050|Data Scientists|15-2051|Data Scientists|        [\n  7\n]|  [\n  "Artificial ...|          44|        Retail Trade|         441|Motor Vehicle and...|        4413|Automotive Parts,...|       44133|Automotive Parts ...|      441330|Automotive Parts ...|
|0cb072af26757b6c4...|         8/2/2024|  2024-08-02 17:08:...|         0|6/2/2024| 8/1/2024|    NULL| [\n  "Job Board"\n]| [\n  "maine.gov"\n]|[\n  "https://job...|         []|               NULL|Oracle Consultant...|Oracle Consultant...|       8/1/2024|            NULL|  133098|Smx Corporation L...|        SMX|               true|      [\n  99\n]| [\n  "No Educatio...|           99|No Education Listed|         NULL|              NULL|              1|Full-time (&gt; 32 h...|                   3|                   3|        false|  NULL|          1|          Remote|               NULL|     NULL|       NULL|{\n  "lat": 44.31...|    QXVndXN0YSwgTUU=|  Augusta, ME| 23011|  Kennebec, ME|12300|Augusta-Watervill...|   23|     Maine|          23011|        Kennebec, ME|          23011|        Kennebec, ME|       12300|Augusta-Watervill...|       12300|Augusta-Watervill...|    56|Administrative an...|   561|Administrative an...|  5613| Employment Services| 56132|Temporary Help Se...|561320|Temporary Help Se...|ET21DDA63780A7DC09| Oracle Consultants|oracle consultant...|[\n  "KS122626T55...|[\n  "Procurement...|[\n  "KS122626T55...|   [\n  "Procurement...|                  []|                  []|                  []|                  []|[\n  "BGSBF3F508F...|[\n  "Oracle Busi...|15-2051.01|Business Intellig...|15-2051.01|Business Intellig...|                  []|                  []|                  []|                  []|                  []|                  []|   15-0000|Computer and Math...|   15-2000|Mathematical Scie...|   15-2050|Data Scientists|   15-2051|Data Scientists|             23|Information Techn...|        231010|Business Intellig...|                  23101012|           Oracle Consultant...|                2310|     Business Intellig...|                     23101012|              Oracle Consultant...|           231010|  Business Intellig...|                   2310|        Business Intellig...|                23|   Information Techn...|15-0000|Computer and Math...|15-2000|Mathematical Scie...|15-2050|Data Scientists|15-2051|Data Scientists|             NULL|                  NULL|          56|Administrative an...|         561|Administrative an...|        5613| Employment Services|       56132|Temporary Help Se...|      561320|Temporary Help Se...|
|85318b12b3331fa49...|         9/6/2024|  2024-09-06 20:32:...|         1|6/2/2024| 7/7/2024|      35| [\n  "Job Board"\n]|[\n  "dejobs.org"\n]|[\n  "https://dej...|         []|               NULL|        Data Analyst|Taking care of pe...|      6/10/2024|               8|39063746|            Sedgwick|   Sedgwick|              false|       [\n  2\n]| [\n  "Bachelor's ...|            2|  Bachelor's degree|         NULL|              NULL|              1|Full-time (&gt; 32 h...|                   5|                NULL|        false|  NULL|          0|          [None]|               NULL|     NULL|       NULL|{\n  "lat": 32.77...|    RGFsbGFzLCBUWA==|   Dallas, TX| 48113|    Dallas, TX|19100|Dallas-Fort Worth...|   48|     Texas|          48113|          Dallas, TX|          48113|          Dallas, TX|       19100|Dallas-Fort Worth...|       19100|Dallas-Fort Worth...|    52|Finance and Insur...|   524|Insurance Carrier...|  5242|Agencies, Brokera...| 52429|Other Insurance R...|524291|    Claims Adjusting|ET3037E0C947A02404|      Data Analysts|        data analyst|[\n  "KS1218W78FG...|[\n  "Management"...|[\n  "ESF3939CE1F...|   [\n  "Exception R...|[\n  "KS683TN76T7...|[\n  "Security Cl...|[\n  "KS1218W78FG...|[\n  "Management"...|[\n  "KS126HY6YLT...|[\n  "Microsoft O...|15-2051.01|Business Intellig...|15-2051.01|Business Intellig...|                  []|                  []|                  []|                  []|                  []|                  []|   15-0000|Computer and Math...|   15-2000|Mathematical Scie...|   15-2050|Data Scientists|   15-2051|Data Scientists|             23|Information Techn...|        231113|Data / Data Minin...|                  23111310|                   Data Analyst|                2311|     Data Analysis and...|                     23111310|                      Data Analyst|           231113|  Data / Data Minin...|                   2311|        Data Analysis and...|                23|   Information Techn...|15-0000|Computer and Math...|15-2000|Mathematical Scie...|15-2050|Data Scientists|15-2051|Data Scientists|             NULL|                  NULL|          52|Finance and Insur...|         524|Insurance Carrier...|        5242|Agencies, Brokera...|       52429|Other Insurance R...|      524291|    Claims Adjusting|
|1b5c3941e54a1889e...|         9/6/2024|  2024-09-06 20:32:...|         1|6/2/2024|7/20/2024|      48| [\n  "Job Board"\n]|[\n  "disabledper...|[\n  "https://www...|         []|               NULL|Sr. Lead Data Mgm...|About this role:\...|      6/12/2024|              10|37615159|         Wells Fargo|Wells Fargo|              false|      [\n  99\n]| [\n  "No Educatio...|           99|No Education Listed|         NULL|              NULL|              1|Full-time (&gt; 32 h...|                   3|                NULL|        false|  NULL|          0|          [None]|               NULL|     NULL|       NULL|{\n  "lat": 33.44...|    UGhvZW5peCwgQVo=|  Phoenix, AZ|  4013|  Maricopa, AZ|38060|Phoenix-Mesa-Chan...|    4|   Arizona|           4013|        Maricopa, AZ|           4013|        Maricopa, AZ|       38060|Phoenix-Mesa-Chan...|       38060|Phoenix-Mesa-Chan...|    52|Finance and Insur...|   522|Credit Intermedia...|  5221|Depository Credit...| 52211|  Commercial Banking|522110|  Commercial Banking|ET2114E0404BA30075|Management Analysts|sr lead data mgmt...|[\n  "KS123QX62QY...|[\n  "Exit Strate...|[\n  "KS123QX62QY...|   [\n  "Exit Strate...|                  []|                  []|[\n  "KS7G6NP6R6L...|[\n  "Reliability...|[\n  "KS4409D76NW...|[\n  "SAS (Softwa...|15-2051.01|Business Intellig...|15-2051.01|Business Intellig...|                  []|                  []|                  []|                  []|                  []|                  []|   15-0000|Computer and Math...|   15-2000|Mathematical Scie...|   15-2050|Data Scientists|   15-2051|Data Scientists|             23|Information Techn...|        231113|Data / Data Minin...|                  23111310|                   Data Analyst|                2311|     Data Analysis and...|                     23111310|                      Data Analyst|           231113|  Data / Data Minin...|                   2311|        Data Analysis and...|                23|   Information Techn...|15-0000|Computer and Math...|15-2000|Mathematical Scie...|15-2050|Data Scientists|15-2051|Data Scientists|        [\n  6\n]|  [\n  "Data Privac...|          52|Finance and Insur...|         522|Credit Intermedia...|        5221|Depository Credit...|       52211|  Commercial Banking|      522110|  Commercial Banking|
|cb5ca25f02bdf25c1...|        6/19/2024|   2024-06-19 07:00:00|         0|6/2/2024|6/17/2024|      15|[\n  "FreeJobBoar...|[\n  "craigslist....|[\n  "https://mod...|         []|               NULL|Comisiones de $10...|Comisiones de $10...|      6/17/2024|              15|       0|        Unclassified|      LH/GM|              false|      [\n  99\n]| [\n  "No Educatio...|           99|No Education Listed|         NULL|              NULL|              3|Part-time / full-...|                NULL|                NULL|        false| 92500|          0|          [None]|               year|   150000|      35000|{\n  "lat": 37.63...|    TW9kZXN0bywgQ0E=|  Modesto, CA|  6099|Stanislaus, CA|33700|         Modesto, CA|    6|California|           6099|      Stanislaus, CA|           6099|      Stanislaus, CA|       33700|         Modesto, CA|       33700|         Modesto, CA|    99|Unclassified Indu...|   999|Unclassified Indu...|  9999|Unclassified Indu...| 99999|Unclassified Indu...|999999|Unclassified Indu...|ET0000000000000000|       Unclassified|comisiones de por...|                  []|                  []|                  []|                     []|                  []|                  []|                  []|                  []|                  []|                  []|15-2051.01|Business Intellig...|15-2051.01|Business Intellig...|                  []|                  []|                  []|                  []|                  []|                  []|   15-0000|Computer and Math...|   15-2000|Mathematical Scie...|   15-2050|Data Scientists|   15-2051|Data Scientists|             23|Information Techn...|        231010|Business Intellig...|                  23101012|           Oracle Consultant...|                2310|     Business Intellig...|                     23101012|              Oracle Consultant...|           231010|  Business Intellig...|                   2310|        Business Intellig...|                23|   Information Techn...|15-0000|Computer and Math...|15-2000|Mathematical Scie...|15-2050|Data Scientists|15-2051|Data Scientists|             NULL|                  NULL|          99|Unclassified Indu...|         999|Unclassified Indu...|        9999|Unclassified Indu...|       99999|Unclassified Indu...|      999999|Unclassified Indu...|
+--------------------+-----------------+----------------------+----------+--------+---------+--------+--------------------+--------------------+--------------------+-----------+-------------------+--------------------+--------------------+---------------+----------------+--------+--------------------+-----------+-------------------+----------------+---------------------+-------------+-------------------+-------------+------------------+---------------+--------------------+--------------------+--------------------+-------------+------+-----------+----------------+-------------------+---------+-----------+--------------------+--------------------+-------------+------+--------------+-----+--------------------+-----+----------+---------------+--------------------+---------------+--------------------+------------+--------------------+------------+--------------------+------+--------------------+------+--------------------+------+--------------------+------+--------------------+------+--------------------+------------------+-------------------+--------------------+--------------------+--------------------+--------------------+-----------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+----------+--------------------+----------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+----------+--------------------+----------+--------------------+----------+---------------+----------+---------------+---------------+--------------------+--------------+--------------------+--------------------------+-------------------------------+--------------------+-------------------------+-----------------------------+----------------------------------+-----------------+----------------------+-----------------------+----------------------------+------------------+-----------------------+-------+--------------------+-------+--------------------+-------+---------------+-------+---------------+-----------------+----------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+
only showing top 5 rows
</code></pre>
</div>
</div>
<div id="8335e474" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>+-----------------+--------+---------+--------+--------------------+--------------------+-------------------+--------------------+--------------------+---------------+----------------+--------+--------------------+-----------+-------------------+----------------+---------------------+-------------+-------------------+-------------+------------------+---------------+--------------------+--------------------+--------------------+-------------+------+-----------+----------------+-------------------+---------+-----------+--------------------+--------------------+-------------+------+--------------+-----+--------------------+-----+----------+---------------+--------------------+---------------+--------------------+------------+--------------------+------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------+-------------------+--------------------+--------------------+--------------------+--------------------+-----------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+----------+--------------------+----------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+----------+--------------------+----------+--------------------+----------+---------------+----------+---------------+---------------+--------------------+--------------+--------------------+--------------------------+-------------------------------+--------------------+-------------------------+-----------------------------+----------------------------------+-----------------+----------------------+-----------------------+----------------------------+------------------+-----------------------+--------------------+--------------------+-------+---------------+-------+---------------+-----------------+----------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+
|LAST_UPDATED_DATE|  POSTED|  EXPIRED|DURATION|        SOURCE_TYPES|             SOURCES|ACTIVE_SOURCES_INFO|           TITLE_RAW|                BODY|MODELED_EXPIRED|MODELED_DURATION| COMPANY|        COMPANY_NAME|COMPANY_RAW|COMPANY_IS_STAFFING|EDUCATION_LEVELS|EDUCATION_LEVELS_NAME|MIN_EDULEVELS| MIN_EDULEVELS_NAME|MAX_EDULEVELS|MAX_EDULEVELS_NAME|EMPLOYMENT_TYPE|EMPLOYMENT_TYPE_NAME|MIN_YEARS_EXPERIENCE|MAX_YEARS_EXPERIENCE|IS_INTERNSHIP|SALARY|REMOTE_TYPE|REMOTE_TYPE_NAME|ORIGINAL_PAY_PERIOD|SALARY_TO|SALARY_FROM|            LOCATION|                CITY|    CITY_NAME|COUNTY|   COUNTY_NAME|  MSA|            MSA_NAME|STATE|STATE_NAME|COUNTY_OUTGOING|COUNTY_NAME_OUTGOING|COUNTY_INCOMING|COUNTY_NAME_INCOMING|MSA_OUTGOING|   MSA_NAME_OUTGOING|MSA_INCOMING|   MSA_NAME_INCOMING|         NAICS2_NAME|         NAICS3_NAME|         NAICS4_NAME|         NAICS5_NAME|         NAICS6_NAME|             TITLE|         TITLE_NAME|         TITLE_CLEAN|              SKILLS|         SKILLS_NAME|  SPECIALIZED_SKILLS|SPECIALIZED_SKILLS_NAME|      CERTIFICATIONS| CERTIFICATIONS_NAME|       COMMON_SKILLS|  COMMON_SKILLS_NAME|     SOFTWARE_SKILLS|SOFTWARE_SKILLS_NAME|      ONET|           ONET_NAME| ONET_2019|      ONET_2019_NAME|                CIP6|           CIP6_NAME|                CIP4|           CIP4_NAME|                CIP2|           CIP2_NAME|SOC_2021_2|     SOC_2021_2_NAME|SOC_2021_3|     SOC_2021_3_NAME|SOC_2021_4|SOC_2021_4_NAME|SOC_2021_5|SOC_2021_5_NAME|LOT_CAREER_AREA|LOT_CAREER_AREA_NAME|LOT_OCCUPATION| LOT_OCCUPATION_NAME|LOT_SPECIALIZED_OCCUPATION|LOT_SPECIALIZED_OCCUPATION_NAME|LOT_OCCUPATION_GROUP|LOT_OCCUPATION_GROUP_NAME|LOT_V6_SPECIALIZED_OCCUPATION|LOT_V6_SPECIALIZED_OCCUPATION_NAME|LOT_V6_OCCUPATION|LOT_V6_OCCUPATION_NAME|LOT_V6_OCCUPATION_GROUP|LOT_V6_OCCUPATION_GROUP_NAME|LOT_V6_CAREER_AREA|LOT_V6_CAREER_AREA_NAME|          SOC_2_NAME|          SOC_3_NAME|  SOC_4|     SOC_4_NAME|  SOC_5|     SOC_5_NAME|LIGHTCAST_SECTORS|LIGHTCAST_SECTORS_NAME|NAICS_2022_2|   NAICS_2022_2_NAME|NAICS_2022_3|   NAICS_2022_3_NAME|NAICS_2022_4|   NAICS_2022_4_NAME|NAICS_2022_5|   NAICS_2022_5_NAME|NAICS_2022_6|   NAICS_2022_6_NAME|
+-----------------+--------+---------+--------+--------------------+--------------------+-------------------+--------------------+--------------------+---------------+----------------+--------+--------------------+-----------+-------------------+----------------+---------------------+-------------+-------------------+-------------+------------------+---------------+--------------------+--------------------+--------------------+-------------+------+-----------+----------------+-------------------+---------+-----------+--------------------+--------------------+-------------+------+--------------+-----+--------------------+-----+----------+---------------+--------------------+---------------+--------------------+------------+--------------------+------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------+-------------------+--------------------+--------------------+--------------------+--------------------+-----------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+----------+--------------------+----------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+----------+--------------------+----------+--------------------+----------+---------------+----------+---------------+---------------+--------------------+--------------+--------------------+--------------------------+-------------------------------+--------------------+-------------------------+-----------------------------+----------------------------------+-----------------+----------------------+-----------------------+----------------------------+------------------+-----------------------+--------------------+--------------------+-------+---------------+-------+---------------+-----------------+----------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+
|         9/6/2024|6/2/2024| 6/8/2024|       6|   [\n  "Company"\n]|[\n  "brassring.c...|               NULL|Enterprise Analys...|31-May-2024\n\nEn...|       6/8/2024|               6|  894731|          Murphy USA| Murphy USA|              false|       [\n  2\n]| [\n  "Bachelor's ...|            2|  Bachelor's degree|         NULL|              NULL|              1|Full-time (&gt; 32 h...|                   2|                   2|        false|  NULL|          0|          [None]|               NULL|     NULL|       NULL|{\n  "lat": 33.20...|RWwgRG9yYWRvLCBBUg==|El Dorado, AR|  5139|     Union, AR|20980|       El Dorado, AR|    5|  Arkansas|           5139|           Union, AR|           5139|           Union, AR|       20980|       El Dorado, AR|       20980|       El Dorado, AR|        Retail Trade|Motor Vehicle and...|Automotive Parts,...|Automotive Parts ...|Automotive Parts ...|ET29C073C03D1F86B4|Enterprise Analysts|enterprise analys...|[\n  "KS126DB6T06...|[\n  "Merchandisi...|[\n  "KS126DB6T06...|   [\n  "Merchandisi...|                  []|                  []|[\n  "KS126706DPF...|[\n  "Mathematics...|[\n  "KS440W865GC...|[\n  "SQL (Progra...|15-2051.01|Business Intellig...|15-2051.01|Business Intellig...|[\n  "45.0601",\n...|[\n  "Economics, ...|[\n  "45.06",\n  ...|[\n  "Economics",...|[\n  "45",\n  "27...|[\n  "Social Scie...|   15-0000|Computer and Math...|   15-2000|Mathematical Scie...|   15-2050|Data Scientists|   15-2051|Data Scientists|             23|Information Techn...|        231010|Business Intellig...|                  23101011|           General ERP Analy...|                2310|     Business Intellig...|                     23101011|              General ERP Analy...|           231010|  Business Intellig...|                   2310|        Business Intellig...|                23|   Information Techn...|Computer and Math...|Mathematical Scie...|15-2050|Data Scientists|15-2051|Data Scientists|        [\n  7\n]|  [\n  "Artificial ...|          44|        Retail Trade|         441|Motor Vehicle and...|        4413|Automotive Parts,...|       44133|Automotive Parts ...|      441330|Automotive Parts ...|
|         8/2/2024|6/2/2024| 8/1/2024|    NULL| [\n  "Job Board"\n]| [\n  "maine.gov"\n]|               NULL|Oracle Consultant...|Oracle Consultant...|       8/1/2024|            NULL|  133098|Smx Corporation L...|        SMX|               true|      [\n  99\n]| [\n  "No Educatio...|           99|No Education Listed|         NULL|              NULL|              1|Full-time (&gt; 32 h...|                   3|                   3|        false|  NULL|          1|          Remote|               NULL|     NULL|       NULL|{\n  "lat": 44.31...|    QXVndXN0YSwgTUU=|  Augusta, ME| 23011|  Kennebec, ME|12300|Augusta-Watervill...|   23|     Maine|          23011|        Kennebec, ME|          23011|        Kennebec, ME|       12300|Augusta-Watervill...|       12300|Augusta-Watervill...|Administrative an...|Administrative an...| Employment Services|Temporary Help Se...|Temporary Help Se...|ET21DDA63780A7DC09| Oracle Consultants|oracle consultant...|[\n  "KS122626T55...|[\n  "Procurement...|[\n  "KS122626T55...|   [\n  "Procurement...|                  []|                  []|                  []|                  []|[\n  "BGSBF3F508F...|[\n  "Oracle Busi...|15-2051.01|Business Intellig...|15-2051.01|Business Intellig...|                  []|                  []|                  []|                  []|                  []|                  []|   15-0000|Computer and Math...|   15-2000|Mathematical Scie...|   15-2050|Data Scientists|   15-2051|Data Scientists|             23|Information Techn...|        231010|Business Intellig...|                  23101012|           Oracle Consultant...|                2310|     Business Intellig...|                     23101012|              Oracle Consultant...|           231010|  Business Intellig...|                   2310|        Business Intellig...|                23|   Information Techn...|Computer and Math...|Mathematical Scie...|15-2050|Data Scientists|15-2051|Data Scientists|             NULL|                  NULL|          56|Administrative an...|         561|Administrative an...|        5613| Employment Services|       56132|Temporary Help Se...|      561320|Temporary Help Se...|
|         9/6/2024|6/2/2024| 7/7/2024|      35| [\n  "Job Board"\n]|[\n  "dejobs.org"\n]|               NULL|        Data Analyst|Taking care of pe...|      6/10/2024|               8|39063746|            Sedgwick|   Sedgwick|              false|       [\n  2\n]| [\n  "Bachelor's ...|            2|  Bachelor's degree|         NULL|              NULL|              1|Full-time (&gt; 32 h...|                   5|                NULL|        false|  NULL|          0|          [None]|               NULL|     NULL|       NULL|{\n  "lat": 32.77...|    RGFsbGFzLCBUWA==|   Dallas, TX| 48113|    Dallas, TX|19100|Dallas-Fort Worth...|   48|     Texas|          48113|          Dallas, TX|          48113|          Dallas, TX|       19100|Dallas-Fort Worth...|       19100|Dallas-Fort Worth...|Finance and Insur...|Insurance Carrier...|Agencies, Brokera...|Other Insurance R...|    Claims Adjusting|ET3037E0C947A02404|      Data Analysts|        data analyst|[\n  "KS1218W78FG...|[\n  "Management"...|[\n  "ESF3939CE1F...|   [\n  "Exception R...|[\n  "KS683TN76T7...|[\n  "Security Cl...|[\n  "KS1218W78FG...|[\n  "Management"...|[\n  "KS126HY6YLT...|[\n  "Microsoft O...|15-2051.01|Business Intellig...|15-2051.01|Business Intellig...|                  []|                  []|                  []|                  []|                  []|                  []|   15-0000|Computer and Math...|   15-2000|Mathematical Scie...|   15-2050|Data Scientists|   15-2051|Data Scientists|             23|Information Techn...|        231113|Data / Data Minin...|                  23111310|                   Data Analyst|                2311|     Data Analysis and...|                     23111310|                      Data Analyst|           231113|  Data / Data Minin...|                   2311|        Data Analysis and...|                23|   Information Techn...|Computer and Math...|Mathematical Scie...|15-2050|Data Scientists|15-2051|Data Scientists|             NULL|                  NULL|          52|Finance and Insur...|         524|Insurance Carrier...|        5242|Agencies, Brokera...|       52429|Other Insurance R...|      524291|    Claims Adjusting|
|         9/6/2024|6/2/2024|7/20/2024|      48| [\n  "Job Board"\n]|[\n  "disabledper...|               NULL|Sr. Lead Data Mgm...|About this role:\...|      6/12/2024|              10|37615159|         Wells Fargo|Wells Fargo|              false|      [\n  99\n]| [\n  "No Educatio...|           99|No Education Listed|         NULL|              NULL|              1|Full-time (&gt; 32 h...|                   3|                NULL|        false|  NULL|          0|          [None]|               NULL|     NULL|       NULL|{\n  "lat": 33.44...|    UGhvZW5peCwgQVo=|  Phoenix, AZ|  4013|  Maricopa, AZ|38060|Phoenix-Mesa-Chan...|    4|   Arizona|           4013|        Maricopa, AZ|           4013|        Maricopa, AZ|       38060|Phoenix-Mesa-Chan...|       38060|Phoenix-Mesa-Chan...|Finance and Insur...|Credit Intermedia...|Depository Credit...|  Commercial Banking|  Commercial Banking|ET2114E0404BA30075|Management Analysts|sr lead data mgmt...|[\n  "KS123QX62QY...|[\n  "Exit Strate...|[\n  "KS123QX62QY...|   [\n  "Exit Strate...|                  []|                  []|[\n  "KS7G6NP6R6L...|[\n  "Reliability...|[\n  "KS4409D76NW...|[\n  "SAS (Softwa...|15-2051.01|Business Intellig...|15-2051.01|Business Intellig...|                  []|                  []|                  []|                  []|                  []|                  []|   15-0000|Computer and Math...|   15-2000|Mathematical Scie...|   15-2050|Data Scientists|   15-2051|Data Scientists|             23|Information Techn...|        231113|Data / Data Minin...|                  23111310|                   Data Analyst|                2311|     Data Analysis and...|                     23111310|                      Data Analyst|           231113|  Data / Data Minin...|                   2311|        Data Analysis and...|                23|   Information Techn...|Computer and Math...|Mathematical Scie...|15-2050|Data Scientists|15-2051|Data Scientists|        [\n  6\n]|  [\n  "Data Privac...|          52|Finance and Insur...|         522|Credit Intermedia...|        5221|Depository Credit...|       52211|  Commercial Banking|      522110|  Commercial Banking|
|        6/19/2024|6/2/2024|6/17/2024|      15|[\n  "FreeJobBoar...|[\n  "craigslist....|               NULL|Comisiones de $10...|Comisiones de $10...|      6/17/2024|              15|       0|        Unclassified|      LH/GM|              false|      [\n  99\n]| [\n  "No Educatio...|           99|No Education Listed|         NULL|              NULL|              3|Part-time / full-...|                NULL|                NULL|        false| 92500|          0|          [None]|               year|   150000|      35000|{\n  "lat": 37.63...|    TW9kZXN0bywgQ0E=|  Modesto, CA|  6099|Stanislaus, CA|33700|         Modesto, CA|    6|California|           6099|      Stanislaus, CA|           6099|      Stanislaus, CA|       33700|         Modesto, CA|       33700|         Modesto, CA|Unclassified Indu...|Unclassified Indu...|Unclassified Indu...|Unclassified Indu...|Unclassified Indu...|ET0000000000000000|       Unclassified|comisiones de por...|                  []|                  []|                  []|                     []|                  []|                  []|                  []|                  []|                  []|                  []|15-2051.01|Business Intellig...|15-2051.01|Business Intellig...|                  []|                  []|                  []|                  []|                  []|                  []|   15-0000|Computer and Math...|   15-2000|Mathematical Scie...|   15-2050|Data Scientists|   15-2051|Data Scientists|             23|Information Techn...|        231010|Business Intellig...|                  23101012|           Oracle Consultant...|                2310|     Business Intellig...|                     23101012|              Oracle Consultant...|           231010|  Business Intellig...|                   2310|        Business Intellig...|                23|   Information Techn...|Computer and Math...|Mathematical Scie...|15-2050|Data Scientists|15-2051|Data Scientists|             NULL|                  NULL|          99|Unclassified Indu...|         999|Unclassified Indu...|        9999|Unclassified Indu...|       99999|Unclassified Indu...|      999999|Unclassified Indu...|
+-----------------+--------+---------+--------+--------------------+--------------------+-------------------+--------------------+--------------------+---------------+----------------+--------+--------------------+-----------+-------------------+----------------+---------------------+-------------+-------------------+-------------+------------------+---------------+--------------------+--------------------+--------------------+-------------+------+-----------+----------------+-------------------+---------+-----------+--------------------+--------------------+-------------+------+--------------+-----+--------------------+-----+----------+---------------+--------------------+---------------+--------------------+------------+--------------------+------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------+-------------------+--------------------+--------------------+--------------------+--------------------+-----------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+----------+--------------------+----------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+----------+--------------------+----------+--------------------+----------+---------------+----------+---------------+---------------+--------------------+--------------+--------------------+--------------------------+-------------------------------+--------------------+-------------------------+-----------------------------+----------------------------------+-----------------+----------------------+-----------------------+----------------------------+------------------+-----------------------+--------------------+--------------------+-------+---------------+-------+---------------+-----------------+----------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+------------+--------------------+
only showing top 5 rows
</code></pre>
</div>
</div>
<div id="ea18d9be" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>TITLE_RAW                               104
TITLE_NAME                               44
TITLE_CLEAN                             140
EMPLOYMENT_TYPE_NAME                     44
REMOTE_TYPE_NAME                         44
COMMON_SKILLS_NAME                       44
SPECIALIZED_SKILLS_NAME                  44
SOFTWARE_SKILLS_NAME                     44
MIN_EDULEVELS_NAME                       44
MAX_EDULEVELS_NAME                    56183
EDUCATION_LEVELS_NAME                    44
MIN_YEARS_EXPERIENCE                  23146
MAX_YEARS_EXPERIENCE                  64068
LOCATION                                 44
STATE                                    44
STATE_NAME                               44
CITY_NAME                                44
COUNTY_NAME                              44
SALARY                                41690
SALARY_FROM                           40100
SALARY_TO                             40100
LOT_V6_OCCUPATION_NAME                   44
LOT_V6_OCCUPATION_GROUP_NAME             44
LOT_V6_SPECIALIZED_OCCUPATION_NAME       44
COMPANY_RAW                             541
dtype: int64</code></pre>
</div>
</div>
<div id="54f2439a" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>(72498, 25)</code></pre>
</div>
</div>
<div id="acc9ccba" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>array(['General ERP Analyst / Consultant', 'Oracle Consultant / Analyst',
       'Data Analyst', 'Enterprise Architect',
       'Business Analyst (General)', 'SAP Analyst / Admin',
       'Business Intelligence Analyst', 'Financial Data Analyst',
       'Data Quality Analyst', 'Healthcare Analyst', None,
       'Marketing Analyst'], dtype=object)</code></pre>
</div>
</div>
<div id="f91cb281" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>TITLE_RAW                                26
TITLE_NAME                                0
TITLE_CLEAN                              56
EMPLOYMENT_TYPE_NAME                      0
REMOTE_TYPE_NAME                          0
COMMON_SKILLS_NAME                        0
SPECIALIZED_SKILLS_NAME                   0
SOFTWARE_SKILLS_NAME                      0
MIN_EDULEVELS_NAME                        0
MAX_EDULEVELS_NAME                    22098
EDUCATION_LEVELS_NAME                     0
MIN_YEARS_EXPERIENCE                   7111
MAX_YEARS_EXPERIENCE                  27052
LOCATION                                  0
STATE                                     0
STATE_NAME                                0
CITY_NAME                                 0
COUNTY_NAME                               0
SALARY                                    0
SALARY_FROM                               0
SALARY_TO                                 0
LOT_V6_OCCUPATION_NAME                    0
LOT_V6_OCCUPATION_GROUP_NAME              0
LOT_V6_SPECIALIZED_OCCUPATION_NAME        0
COMPANY_RAW                             227
dtype: int64</code></pre>
</div>
</div>
<div id="af40cf90" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>(30808, 25)</code></pre>
</div>
</div>
<div id="8a1989be" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>LOT_V6_SPECIALIZED_OCCUPATION_NAME
Data Analyst                        27832
General ERP Analyst / Consultant     9931
Enterprise Architect                 8212
Oracle Consultant / Analyst          8141
SAP Analyst / Admin                  7734
Business Analyst (General)           4326
Business Intelligence Analyst        3639
Financial Data Analyst               1155
Data Quality Analyst                 1070
Healthcare Analyst                    261
Marketing Analyst                     153
Name: count, dtype: int64</code></pre>
</div>
</div>
<section id="plot-2-select-lot_name_specific-mean-salary-job-demand" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> PLOT 2 Select (LOT_NAME_SPECIFIC) Mean Salary &amp; Job Demand</h1>
<div id="50119109" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/data_analysis-cell-12-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="4836a79d" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>LOT_V6_SPECIALIZED_OCCUPATION_NAME
Business Analyst (General)          100888.607317
Business Intelligence Analyst       108886.397778
Data Analyst                        103796.067383
Data Quality Analyst                 99441.350000
Enterprise Architect                162408.228546
Financial Data Analyst               64161.114219
General ERP Analyst / Consultant    129766.138806
Healthcare Analyst                   93609.968085
Marketing Analyst                    97650.153846
Oracle Consultant / Analyst         138141.414918
SAP Analyst / Admin                 115745.803736
Name: SALARY, dtype: float64</code></pre>
</div>
</div>
<div id="1bdb4653" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/data_analysis-cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="plot-1-geographic-distribution-of-salary-and-job-demand" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Plot 1 Geographic distribution of salary and job demand</h1>
</section>
<section id="plot-3-extract-the-top-10-skills-by-category" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Plot 3 Extract the top 10 skills by category</h1>
<div id="8cf7777b" class="cell" data-execution_count="18">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/data_analysis-cell-18-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="6a127fed" class="cell" data-execution_count="19">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/data_analysis-cell-19-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/data_analysis-cell-19-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/data_analysis-cell-19-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/data_analysis-cell-19-output-4.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/data_analysis-cell-19-output-5.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/data_analysis-cell-19-output-6.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/data_analysis-cell-19-output-7.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/data_analysis-cell-19-output-8.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/data_analysis-cell-19-output-9.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/data_analysis-cell-19-output-10.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/data_analysis-cell-19-output-11.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="skill-gap-analysis" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> Skill Gap Analysis</h1>
<div id="ddaf0429" class="cell" data-execution_count="20">
<div class="cell-output cell-output-stdout">
<pre><code>Required Skills for Data Analyst Role:
- Communication
- Management
- Microsoft Excel
- Problem Solving
- Detail Oriented
- Leadership
- Operations
- Research
- Presentations
- Writing
- Data Analysis
- SQL (Programming Language)
- Python (Programming Language)
- Tableau (Business Intelligence Software)
- Dashboard
- Computer Science
- Power BI
- Statistics
- Data Visualization
- Data Management
- R (Programming Language)
- Microsoft Office
- Microsoft PowerPoint
- SAS (Software)</code></pre>
</div>
</div>
<div id="e0c7e221" class="cell" data-execution_count="21">
<div class="cell-output cell-output-stdout">
<pre><code>                                       Skill  Marco  Millie
0                              Communication      4       4
1                                 Management      2       3
2                            Microsoft Excel      3       4
3                            Problem Solving      4       4
4                            Detail Oriented      4       3
5                                 Leadership      4       4
6                                 Operations      2       2
7                                   Research      4       3
8                              Presentations      4       3
9                                    Writing      3       2
10                             Data Analysis      4       3
11                SQL (Programming Language)      2       2
12             Python (Programming Language)      3       3
13  Tableau (Business Intelligence Software)      2       1
14                                 Dashboard      2       2
15                          Computer Science      1       1
16                                  Power BI      2       2
17                                Statistics      3       2
18                        Data Visualization      4       3
19                           Data Management      2       3
20                  R (Programming Language)      2       2
21                          Microsoft Office      4       4
22                      Microsoft PowerPoint      3       4
23                            SAS (Software)      1       1</code></pre>
</div>
</div>
<div id="06c9cce8" class="cell" data-execution_count="23">
<div class="cell-output cell-output-stdout">
<pre><code>Marco's average rating: 2.88 / 5.00
Millie's average rating: 2.71 / 5.00</code></pre>
</div>
</div>
</section>
<section id="plot-4-kmeans-clustering-for-naics2_name-skills-for-analyst-position" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> PLOT 4 Kmeans clustering for NAICS2_NAME skills (for Analyst position)</h1>
<div id="cb070fbf" class="cell" data-execution_count="25">
<div class="cell-output cell-output-stdout">
<pre><code>['Enterprise Analysts' 'Data Analysts' 'Management Analysts' ...
 'Oracle Solution Architects' 'Donor Relations Managers'
 'Philanthropy Interns']</code></pre>
</div>
</div>
<div id="6e8d80ce" class="cell" data-execution_count="26">
<div class="cell-output cell-output-stdout">
<pre><code>['access' 'accounting' 'analysis' 'analytical' 'analytics' 'and' 'apache'
 'application' 'applications' 'azure']</code></pre>
</div>
</div>
<div id="576a68c4" class="cell" data-execution_count="27">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/data_analysis-cell-27-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="00693b5e" class="cell" data-execution_count="33">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/data_analysis-cell-31-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="17489d74" class="cell" data-execution_count="34">
<div class="cell-output cell-output-stdout">
<pre><code>                    PC1       PC2
access         0.017736  0.076920
accounting    -0.011342  0.004536
amazon         0.030360 -0.012343
analysis       0.077540  0.031537
analytical     0.014053  0.013053
...                 ...       ...
user          -0.000095  0.006242
visualization  0.039281 -0.001602
warehousing    0.025778  0.009641
workflow       0.002306  0.004493
writing        0.006385  0.023276

[100 rows x 2 columns]</code></pre>
</div>
</div>
</section>
<section id="plot-5-random-forest-classification" class="level1" data-number="14">
<h1 data-number="14"><span class="header-section-number">14</span> PLOT 5 Random Forest Classification</h1>
<div id="9c644a30" class="cell">
<div class="cell-output cell-output-display" data-execution_count="27">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">SALARY</th>
<th data-quarto-table-cell-role="th">STATE</th>
<th data-quarto-table-cell-role="th">COMMON_SKILLS_NAME</th>
<th data-quarto-table-cell-role="th">SPECIALIZED_SKILLS_NAME</th>
<th data-quarto-table-cell-role="th">SOFTWARE_SKILLS_NAME</th>
<th data-quarto-table-cell-role="th">skills_text</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>110155.0</td>
<td>AR</td>
<td>[\n "Presentations",\n "Data Reporting",\n ...</td>
<td>[\n "Power BI",\n "Qlik Sense (Data Analytic...</td>
<td>[\n "Power BI",\n "Qlik Sense (Data Analytic...</td>
<td>presentations data_reporting operations power_...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>92962.0</td>
<td>NY</td>
<td>[\n "Prioritization",\n "Google Sheets",\n ...</td>
<td>[\n "Salesforce",\n "Google Docs",\n "Produ...</td>
<td>[\n "Salesforce",\n "Google Docs",\n "Produ...</td>
<td>prioritization google_sheets microsoft_powerpo...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>107645.0</td>
<td>CA</td>
<td>[\n "Research",\n "Information Technology",\...</td>
<td>[\n "Regression Testing",\n "Flight Testing"...</td>
<td>[\n "Python (Programming Language)",\n "Visu...</td>
<td>research information_technology communication ...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">19</td>
<td>170000.0</td>
<td>CA</td>
<td>[\n "Curiosity",\n "Interpersonal Communicat...</td>
<td>[\n "Business Continuity Planning",\n "Growt...</td>
<td>[\n "C (Programming Language)",\n "Python (P...</td>
<td>curiosity interpersonal_communications influen...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">20</td>
<td>110155.0</td>
<td>TN</td>
<td>[\n "Presentations",\n "Data Reporting",\n ...</td>
<td>[\n "Power BI",\n "Qlik Sense (Data Analytic...</td>
<td>[\n "Power BI",\n "Qlik Sense (Data Analytic...</td>
<td>presentations data_reporting operations power_...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">72482</td>
<td>117500.0</td>
<td>CA</td>
<td>[\n "Analytical Skills",\n "Microsoft PowerP...</td>
<td>[\n "Healthcare Industry Knowledge",\n "Life...</td>
<td>[\n "Microsoft PowerPoint",\n "Microsoft Off...</td>
<td>analytical_skills microsoft_powerpoint communi...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">72483</td>
<td>80750.0</td>
<td>IL</td>
<td>[\n "Research",\n "Presentations",\n "Forec...</td>
<td>[\n "Marketing Strategies",\n "Power BI",\n ...</td>
<td>[\n "Power BI",\n "Shiny (R Package)",\n "A...</td>
<td>research presentations forecasting communicati...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">72485</td>
<td>91520.0</td>
<td>GA</td>
<td>[\n "Customer Service",\n "Management",\n "...</td>
<td>[\n "Organizational Communications",\n "Fina...</td>
<td>[\n "Business Intelligence Tools",\n "Report...</td>
<td>customer_service management analytical_skills ...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">72492</td>
<td>158855.0</td>
<td>NC</td>
<td>[\n "Data Reporting",\n "Microsoft PowerPoin...</td>
<td>[\n "Data Extraction",\n "Data Manipulation"...</td>
<td>[\n "Microsoft PowerPoint",\n "Python (Progr...</td>
<td>data_reporting microsoft_powerpoint influencin...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">72495</td>
<td>72800.0</td>
<td>MI</td>
<td>[\n "Detail Oriented",\n "Microsoft Excel",\...</td>
<td>[\n "Workflow Management",\n "Acceptance Tes...</td>
<td>[\n "Microsoft Excel",\n "Dashboard",\n "Ta...</td>
<td>detail_oriented microsoft_excel customer_servi...</td>
</tr>
</tbody>
</table>

<p>12377 rows × 6 columns</p>
</div>
</div>
</div>
<div id="28bbd0a5" class="cell">
<div class="cell-output cell-output-display" data-execution_count="28">
<style>#sk-container-id-1 {
  /* Definition of color scheme common for light and dark mode */
  --sklearn-color-text: #000;
  --sklearn-color-text-muted: #666;
  --sklearn-color-line: gray;
  /* Definition of color scheme for unfitted estimators */
  --sklearn-color-unfitted-level-0: #fff5e6;
  --sklearn-color-unfitted-level-1: #f6e4d2;
  --sklearn-color-unfitted-level-2: #ffe0b3;
  --sklearn-color-unfitted-level-3: chocolate;
  /* Definition of color scheme for fitted estimators */
  --sklearn-color-fitted-level-0: #f0f8ff;
  --sklearn-color-fitted-level-1: #d4ebff;
  --sklearn-color-fitted-level-2: #b3dbfd;
  --sklearn-color-fitted-level-3: cornflowerblue;

  /* Specific color for light theme */
  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));
  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));
  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));
  --sklearn-color-icon: #696969;

  @media (prefers-color-scheme: dark) {
    /* Redefinition of color scheme for dark theme */
    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));
    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));
    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));
    --sklearn-color-icon: #878787;
  }
}

#sk-container-id-1 {
  color: var(--sklearn-color-text);
}

#sk-container-id-1 pre {
  padding: 0;
}

#sk-container-id-1 input.sk-hidden--visually {
  border: 0;
  clip: rect(1px 1px 1px 1px);
  clip: rect(1px, 1px, 1px, 1px);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
}

#sk-container-id-1 div.sk-dashed-wrapped {
  border: 1px dashed var(--sklearn-color-line);
  margin: 0 0.4em 0.5em 0.4em;
  box-sizing: border-box;
  padding-bottom: 0.4em;
  background-color: var(--sklearn-color-background);
}

#sk-container-id-1 div.sk-container {
  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`
     but bootstrap.min.css set `[hidden] { display: none !important; }`
     so we also need the `!important` here to be able to override the
     default hidden behavior on the sphinx rendered scikit-learn.org.
     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */
  display: inline-block !important;
  position: relative;
}

#sk-container-id-1 div.sk-text-repr-fallback {
  display: none;
}

div.sk-parallel-item,
div.sk-serial,
div.sk-item {
  /* draw centered vertical line to link estimators */
  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));
  background-size: 2px 100%;
  background-repeat: no-repeat;
  background-position: center center;
}

/* Parallel-specific style estimator block */

#sk-container-id-1 div.sk-parallel-item::after {
  content: "";
  width: 100%;
  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);
  flex-grow: 1;
}

#sk-container-id-1 div.sk-parallel {
  display: flex;
  align-items: stretch;
  justify-content: center;
  background-color: var(--sklearn-color-background);
  position: relative;
}

#sk-container-id-1 div.sk-parallel-item {
  display: flex;
  flex-direction: column;
}

#sk-container-id-1 div.sk-parallel-item:first-child::after {
  align-self: flex-end;
  width: 50%;
}

#sk-container-id-1 div.sk-parallel-item:last-child::after {
  align-self: flex-start;
  width: 50%;
}

#sk-container-id-1 div.sk-parallel-item:only-child::after {
  width: 0;
}

/* Serial-specific style estimator block */

#sk-container-id-1 div.sk-serial {
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: var(--sklearn-color-background);
  padding-right: 1em;
  padding-left: 1em;
}


/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is
clickable and can be expanded/collapsed.
- Pipeline and ColumnTransformer use this feature and define the default style
- Estimators will overwrite some part of the style using the `sk-estimator` class
*/

/* Pipeline and ColumnTransformer style (default) */

#sk-container-id-1 div.sk-toggleable {
  /* Default theme specific background. It is overwritten whether we have a
  specific estimator or a Pipeline/ColumnTransformer */
  background-color: var(--sklearn-color-background);
}

/* Toggleable label */
#sk-container-id-1 label.sk-toggleable__label {
  cursor: pointer;
  display: flex;
  width: 100%;
  margin-bottom: 0;
  padding: 0.5em;
  box-sizing: border-box;
  text-align: center;
  align-items: start;
  justify-content: space-between;
  gap: 0.5em;
}

#sk-container-id-1 label.sk-toggleable__label .caption {
  font-size: 0.6rem;
  font-weight: lighter;
  color: var(--sklearn-color-text-muted);
}

#sk-container-id-1 label.sk-toggleable__label-arrow:before {
  /* Arrow on the left of the label */
  content: "▸";
  float: left;
  margin-right: 0.25em;
  color: var(--sklearn-color-icon);
}

#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {
  color: var(--sklearn-color-text);
}

/* Toggleable content - dropdown */

#sk-container-id-1 div.sk-toggleable__content {
  max-height: 0;
  max-width: 0;
  overflow: hidden;
  text-align: left;
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-0);
}

#sk-container-id-1 div.sk-toggleable__content.fitted {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-0);
}

#sk-container-id-1 div.sk-toggleable__content pre {
  margin: 0.2em;
  border-radius: 0.25em;
  color: var(--sklearn-color-text);
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-0);
}

#sk-container-id-1 div.sk-toggleable__content.fitted pre {
  /* unfitted */
  background-color: var(--sklearn-color-fitted-level-0);
}

#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {
  /* Expand drop-down */
  max-height: 200px;
  max-width: 100%;
  overflow: auto;
}

#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {
  content: "▾";
}

/* Pipeline/ColumnTransformer-specific style */

#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {
  color: var(--sklearn-color-text);
  background-color: var(--sklearn-color-unfitted-level-2);
}

#sk-container-id-1 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {
  background-color: var(--sklearn-color-fitted-level-2);
}

/* Estimator-specific style */

/* Colorize estimator box */
#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-2);
}

#sk-container-id-1 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-2);
}

#sk-container-id-1 div.sk-label label.sk-toggleable__label,
#sk-container-id-1 div.sk-label label {
  /* The background is the default theme color */
  color: var(--sklearn-color-text-on-default-background);
}

/* On hover, darken the color of the background */
#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {
  color: var(--sklearn-color-text);
  background-color: var(--sklearn-color-unfitted-level-2);
}

/* Label box, darken color on hover, fitted */
#sk-container-id-1 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {
  color: var(--sklearn-color-text);
  background-color: var(--sklearn-color-fitted-level-2);
}

/* Estimator label */

#sk-container-id-1 div.sk-label label {
  font-family: monospace;
  font-weight: bold;
  display: inline-block;
  line-height: 1.2em;
}

#sk-container-id-1 div.sk-label-container {
  text-align: center;
}

/* Estimator-specific */
#sk-container-id-1 div.sk-estimator {
  font-family: monospace;
  border: 1px dotted var(--sklearn-color-border-box);
  border-radius: 0.25em;
  box-sizing: border-box;
  margin-bottom: 0.5em;
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-0);
}

#sk-container-id-1 div.sk-estimator.fitted {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-0);
}

/* on hover */
#sk-container-id-1 div.sk-estimator:hover {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-2);
}

#sk-container-id-1 div.sk-estimator.fitted:hover {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-2);
}

/* Specification for estimator info (e.g. "i" and "?") */

/* Common style for "i" and "?" */

.sk-estimator-doc-link,
a:link.sk-estimator-doc-link,
a:visited.sk-estimator-doc-link {
  float: right;
  font-size: smaller;
  line-height: 1em;
  font-family: monospace;
  background-color: var(--sklearn-color-background);
  border-radius: 1em;
  height: 1em;
  width: 1em;
  text-decoration: none !important;
  margin-left: 0.5em;
  text-align: center;
  /* unfitted */
  border: var(--sklearn-color-unfitted-level-1) 1pt solid;
  color: var(--sklearn-color-unfitted-level-1);
}

.sk-estimator-doc-link.fitted,
a:link.sk-estimator-doc-link.fitted,
a:visited.sk-estimator-doc-link.fitted {
  /* fitted */
  border: var(--sklearn-color-fitted-level-1) 1pt solid;
  color: var(--sklearn-color-fitted-level-1);
}

/* On hover */
div.sk-estimator:hover .sk-estimator-doc-link:hover,
.sk-estimator-doc-link:hover,
div.sk-label-container:hover .sk-estimator-doc-link:hover,
.sk-estimator-doc-link:hover {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-3);
  color: var(--sklearn-color-background);
  text-decoration: none;
}

div.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,
.sk-estimator-doc-link.fitted:hover,
div.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,
.sk-estimator-doc-link.fitted:hover {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-3);
  color: var(--sklearn-color-background);
  text-decoration: none;
}

/* Span, style for the box shown on hovering the info icon */
.sk-estimator-doc-link span {
  display: none;
  z-index: 9999;
  position: relative;
  font-weight: normal;
  right: .2ex;
  padding: .5ex;
  margin: .5ex;
  width: min-content;
  min-width: 20ex;
  max-width: 50ex;
  color: var(--sklearn-color-text);
  box-shadow: 2pt 2pt 4pt #999;
  /* unfitted */
  background: var(--sklearn-color-unfitted-level-0);
  border: .5pt solid var(--sklearn-color-unfitted-level-3);
}

.sk-estimator-doc-link.fitted span {
  /* fitted */
  background: var(--sklearn-color-fitted-level-0);
  border: var(--sklearn-color-fitted-level-3);
}

.sk-estimator-doc-link:hover span {
  display: block;
}

/* "?"-specific style due to the `<a>` HTML tag */

#sk-container-id-1 a.estimator_doc_link {
  float: right;
  font-size: 1rem;
  line-height: 1em;
  font-family: monospace;
  background-color: var(--sklearn-color-background);
  border-radius: 1rem;
  height: 1rem;
  width: 1rem;
  text-decoration: none;
  /* unfitted */
  color: var(--sklearn-color-unfitted-level-1);
  border: var(--sklearn-color-unfitted-level-1) 1pt solid;
}

#sk-container-id-1 a.estimator_doc_link.fitted {
  /* fitted */
  border: var(--sklearn-color-fitted-level-1) 1pt solid;
  color: var(--sklearn-color-fitted-level-1);
}

/* On hover */
#sk-container-id-1 a.estimator_doc_link:hover {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-3);
  color: var(--sklearn-color-background);
  text-decoration: none;
}

#sk-container-id-1 a.estimator_doc_link.fitted:hover {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-3);
}
</style><div id="sk-container-id-1" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>CountVectorizer(binary=True,
                vocabulary=['mapreduce', 'microsoft_excel', 'data_engineering',
                            'influencing_skills', 'governance', 'data_entry',
                            'detail_oriented', 'leadership',
                            'data_architecture', 'team_building',
                            'decision_science', 'hematology', 'react',
                            'programming_language', 'data_modeling',
                            'organizational_skills', 'taxonomy', 'triage',
                            'apache_kafka', 'data_quality', 'business_analysis',
                            'continuing_care', 'time_management',
                            'policy_development', 'data_strategy', 'research',
                            'pyspark', 'consulting', 'data_infrastructure',
                            'python_', ...])</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item"><div class="sk-estimator fitted sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-1" type="checkbox" checked=""><label for="sk-estimator-id-1" class="sk-toggleable__label fitted sk-toggleable__label-arrow"><div><div>CountVectorizer</div></div><div><a class="sk-estimator-doc-link fitted" rel="noreferrer" target="_blank" href="https://scikit-learn.org/1.6/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html">?<span>Documentation for CountVectorizer</span></a><span class="sk-estimator-doc-link fitted">i<span>Fitted</span></span></div></label><div class="sk-toggleable__content fitted"><pre>CountVectorizer(binary=True,
                vocabulary=['mapreduce', 'microsoft_excel', 'data_engineering',
                            'influencing_skills', 'governance', 'data_entry',
                            'detail_oriented', 'leadership',
                            'data_architecture', 'team_building',
                            'decision_science', 'hematology', 'react',
                            'programming_language', 'data_modeling',
                            'organizational_skills', 'taxonomy', 'triage',
                            'apache_kafka', 'data_quality', 'business_analysis',
                            'continuing_care', 'time_management',
                            'policy_development', 'data_strategy', 'research',
                            'pyspark', 'consulting', 'data_infrastructure',
                            'python_', ...])</pre></div> </div></div></div></div>
</div>
</div>
<div id="7a6eda4e" class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Fitting 3 folds for each of 15 candidates, totalling 45 fits
Best Hyperparameters: {'max_depth': 24, 'max_features': 44, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 149}
RMSE: 24094.44
R² Score: 0.635</code></pre>
</div>
</div>
<div id="9d77feee" class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>['advanced_analytics', 'advocacy', 'agile_methodology', 'alation_data_catalog', 'analytical_skills', 'apache_hadoop', 'apache_kafka', 'apache_spark', 'balancing_', 'banking', 'big_data', 'billing', 'biotechnology', 'business_acumen', 'business_analysis', 'business_analytics', 'business_intelligence_software', 'business_requirements', 'business_statistics', 'business_strategies', 'communication', 'consulting', 'continuing_care', 'curiosity', 'cyber_threat_intelligence', 'dashboard', 'data_acquisition', 'data_analysis', 'data_architecture', 'data_collection', 'data_engineering', 'data_entry', 'data_governance', 'data_infrastructure', 'data_lineage', 'data_modeling', 'data_quality', 'data_science', 'data_strategy', 'data_synthesis', 'data_warehousing', 'decision_science', 'deep_learning', 'detail_oriented', 'diplomacy', 'emotional_intelligence', 'ethernet_physical_layer', 'etl', 'extract_transform_load_', 'finance', 'financial_services', 'generally_accepted_accounting_principles', 'governance', 'hematology', 'hospital_medicine', 'influencing_skills', 'innovation', 'leadership', 'machine_learning', 'management', 'mapreduce', 'market_trend', 'marketing_strategies', 'mentorship', 'microsoft_azure', 'microsoft_excel', 'microsoft_outlook', 'natural_language_processing_', 'nlp', 'node', 'ontologies', 'operations', 'organizational_skills', 'organizational_strategy', 'policy_development', 'power_bi', 'prioritization', 'problem_solving', 'programming_language', 'project_management', 'pyspark', 'python_', 'r_', 'react', 'regulatory_affairs', 'research', 'resilience', 'rockwell_factorytalk', 'scalability', 'software_engineering', 'sql_', 'stakeholder_management', 'taxonomy', 'team_building', 'team_leadership', 'thought_leadership', 'time_management', 'tooling', 'triage', 'visionary']</code></pre>
</div>
</div>
<div id="efb59384" class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Predicted Salary: $91,979.83</code></pre>
</div>
</div>
</section>
<a class="quarto-notebook-link" id="nblink-1" href="data_analysis-preview.html#bed9e175">Source: PLOT 2  Select (LOT_NAME_SPECIFIC) Mean Salary &amp; Job Demand</a></div>
</section>
<section id="educational-development" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="educational-development"><span class="header-section-number">14.1</span> Educational Development</h2>
<p><strong>Marco’s Educational Recommendations</strong>:</p>
<p>SQL for Data Science – Coursera（UC Davis）</p>
<p>Data Engineering with Python – Coursera（IBM）</p>
<p>Power BI Essential Training – LinkedIn Learning</p>
<p><strong>Millie’s Educational Recommendations</strong>:</p>
<p>Intro to SQL – Mode Analytics</p>
<p>Statistics for Data Science – Coursera</p>
<p>Tableau for Analytics – Coursera</p>
<p><strong>Supplement skills and knowledge through courses and build a solid theoretical foundation and choose tool courses that have the most obvious gap with current skills, and combine them with practical exercises to enhance the absorption effect.</strong></p>
</section>
<section id="project-based-application" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="project-based-application"><span class="header-section-number">14.2</span> Project-Based Application</h2>
<p><strong>Marco’s Project Exercises</strong>:</p>
<p>Netflix Movies &amp; TV Shows (model development and dashboard implementation) – Kaggle</p>
<p>NASA Bearing Dataset (R&amp;D application scenario) – Kaggle</p>
<p><strong>Millie’s Project Exercises</strong>:</p>
<p>Used-Car Data (SQL and dashboard operations) – Kaggle</p>
<p>Hotel Booking Demand (simulated consultant scenario analysis) – Kaggle</p>
<p><strong>Apply skills to real data sets through actual project operations, accumulate works and experience (such as business analysis, consulting, data science) and organize them into a portfolio.</strong></p>
</section>
<section id="skills-to-improve" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="skills-to-improve"><span class="header-section-number">14.3</span> Skills to Improve</h2>
<p><strong>Marco’s Key Skills</strong>:</p>
<p>Python、SQL、Dashboarding、Machine Learning</p>
<p><strong>Millie’s Key Skills</strong>:</p>
<p>SQL、Problem Solving、Dashboarding、Data Analysis、Statistics</p>
<p><strong>Clearly list the technologies and capabilities that need to be strengthened, make strategic plans. Prioritize strengthening core data skills (such as SQL, Dashboarding), and simultaneously improve logical reasoning and problem-solving abilities.</strong></p>
<p>Our analysis of Business Analytics, Data Science, and Machine Learning trends reveals a clear alignment between high-demand roles and specialized skill sets. By mapping job postings and average salaries, we observed that roles in data-related fields offer both abundant opportunities and competitive compensation. The dual bar chart comparing job counts and salaries for specialized occupations further confirms the premium placed on data-driven expertise.</p>
<p>Through skill-based PCA clustering, we identified distinct groups of in-demand competencies, ranging from technical programming skills to business-oriented and communication strengths. This skill landscape highlights the importance of both technical fluency and strategic thinking in the analytics workforce.</p>
<p>In our own team, we conducted a skills assessment and used a random forest model to understand the key features driving role readiness. This was followed by a personalized career strategy map, where each member outlined their skills to improve and aligned courses and projects to build targeted capabilities. This individualized approach not only bridges current skill gaps but also ensures continuous alignment with evolving industry expectations.</p>
<p>In conclusion, the future of analytics careers lies in a balanced development of technical, analytical, and soft skills. By staying informed of labor market trends and proactively upskilling through structured strategies, professionals can position themselves to thrive in this dynamic, data-driven economy.</p>



</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-time2024meta" class="csl-entry" role="listitem">
<span class="smallcaps">Allyn, B.</span> (2024): <span>“Meta Is Building AI on an Industrial Scale—and It’s Coming for Your Data,”</span> <em>TIME</em>, <a href="https://time.com/7294699/meta-scale-ai-data-industry/">https://time.com/7294699/meta-scale-ai-data-industry/</a>.
</div>
<div id="ref-bone2023skills" class="csl-entry" role="listitem">
<span class="smallcaps">Bone, M., T. Conroy, and A. Tan</span>. (2023): <span>“Skills or Degree? The Rise of Skill-Based Hiring for AI and Green Jobs,”</span> <em>arXiv preprint</em>, <a href="https://arxiv.org/abs/2310.05647">https://arxiv.org/abs/2310.05647</a>.
</div>
<div id="ref-cobloom2025datascience" class="csl-entry" role="listitem">
<span class="smallcaps">Cobloom</span>. (2025): <span>“Top in-Demand Data Science Skills in 2025,”</span> <em>Cobloom Careers Blog</em>, <a href="https://www.cobloom.com/blog/data-science-skills-2025">https://www.cobloom.com/blog/data-science-skills-2025</a>.
</div>
<div id="ref-gulati2025generative" class="csl-entry" role="listitem">
<span class="smallcaps">Gulati, P., A. Venkataraman, and S. Raj</span>. (2025): <span>“Generative AI Adoption and Higher-Order Skill Demands: Evidence from u.s. Job Postings,”</span> <em>arXiv preprint</em>, <a href="https://arxiv.org/abs/2405.10312">https://arxiv.org/abs/2405.10312</a>.
</div>
<div id="ref-pwc2024barometer" class="csl-entry" role="listitem">
<span class="smallcaps">PwC</span>. (2024): <span>“AI Jobs Barometer: Tracking the Impact of AI on Jobs,”</span><a href="https://www.pwc.com/gx/en/issues/artificial-intelligence/ai-jobs-barometer.html">https://www.pwc.com/gx/en/issues/artificial-intelligence/ai-jobs-barometer.html</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/MarcoHortiales\.github\.io\/AD688-GROUP3-JOB-MARKET-ANALYSIS\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>